### ISSUE TITLE
Question about sinkhorn and attention weights.

### ISSUE THREAD

**Issue by XuyangBai** [yhenon/pytorch-superglue#1]
Hi @yhenon Thank you for your sharing, I also want to try SuperGlue for my project and I have some questions towards your implementation
1. Why in your code the attention weight is divided by `11.313708498984761` in 
https://github.com/yhenon/pytorch-superglue/blob/6739039cada3a1c2866b0e89ece8f0d3194c5cc2/superglue/model.py#L57

2. Why you do the following operation? I think the `costs_with_dustbin` measure the similarity between each node pair, and the higher the more similar. So why you use `1 - costs_with_dustbin` for sinkhorn?
https://github.com/yhenon/pytorch-superglue/blob/6739039cada3a1c2866b0e89ece8f0d3194c5cc2/superglue/model.py#L146

3.  Could you please example a little bit about the `sinkhorn` function? Basically I think the sinkhorn should alternate between normalizing the row-wise and normalizing the col-wise, but I don't understand the algorithm written by you. And the returned matrix is not between `[0, 1]`

Thanks a lot.

**Comment by yhenon** [comment]
>Why in your code the attention weight is divided by 11.313708498984761 

It's standard to normalize the transformer weight by `sqrt(D)` where `D` is the dimension (see for example here: https://arxiv.org/abs/2002.03983 (in this case I hard coded sqrt(128), kind of lazy). I'm not sure if the authors don't do it or just missed it in the paper.

>Why you do the following operation

The sinkhorn algorithm produces assignments between pairs with low scores (the score acts as a cost). But we have similarity measures, which are high for similar points. So we convert from a similarity to a distance.

>Could you please example a little bit about the sinkhorn function


 I just adapted the code from https://pot.readthedocs.io/en/stable/all.html#ot.sinkhorn , but in pytorch and with batching. In our version, we pass an `NxM` matrix of distances, a vector `a` of size `N` of source histograms, and a vector `b` of size `M` of target histogram. So we dont expect the solution rows and cols to sum up to 1, but to sum up to `a` and `b`. 
In terms of the algorithm, I'm not 100% sure how the versions compare -- clearly it's a different procedure, but I don't fully understand the difference

**Comment by XuyangBai** [comment]
Thanks a lot. That makes sense to me
